# Generated by Django 2.1.7 on 2024-05-31 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('order_state', models.IntegerField(choices=[(0, '进行中'), (1, '已完成'), (2, '已取消'), (3, '申诉中')])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('pay_method', models.IntegerField(choices=[(0, '未支付'), (1, '支付宝'), (2, '微信')])),
                ('result_path', models.CharField(max_length=1024)),
                ('dataset_path', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(default=None, max_length=200)),
                ('taskDescription', models.TextField()),
                ('taskNumber', models.IntegerField(default=1)),
                ('taskRemainingNumber', models.IntegerField(default=None)),
                ('taskRank', models.IntegerField()),
                ('taskType', models.PositiveSmallIntegerField(choices=[(0, '文本'), (1, '图像'), (2, '音频')], default=0)),
                ('perTaskPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createTime', models.DateTimeField(null=True)),
                ('filePath', models.TextField(blank=True)),
                ('task_status', models.CharField(default='已发布', max_length=50)),
                ('modify_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('permission', models.PositiveSmallIntegerField(choices=[(0, '发布者'), (1, '标注者')])),
                ('level', models.IntegerField(choices=[(1, '等级1'), (2, '等级2'), (3, '等级3'), (4, '等级4'), (5, '等级5')], default=1)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('password', models.CharField(max_length=512)),
                ('resumePath', models.TextField(blank=True)),
                ('approvalResult', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAnnodationSystem.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_orders', to='DataAnnodationSystem.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_orders', to='DataAnnodationSystem.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAnnodationSystem.Task'),
        ),
    ]
