# Generated by Django 2.1.7 on 2024-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnnodationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modifyTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='createTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
