# Generated by Django 2.1.7 on 2024-06-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnnodationSystem', '0002_auto_20240531_1209'),
    ]

    operations = [

    ]
