# Generated by Django 2.1.7 on 2024-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnnodationSystem', '0003_auto_20240601_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True),
        ),
    ]
