# Generated by Django 2.1.7 on 2024-06-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnnodationSystem', '0006_auto_20240602_1240'),
    ]

    operations = [

    ]
